from model.person import Person
from model.student import Student
from model.administrator import Administrator
from model.department import Department
from model.course import Course
from model.course_section import CourseSection
from model.registration import Registration
from model.semester import Semester
from model.schedule import Schedule
