from model.user import User
from model.admin import Admin
from model.student import Student
from model.course import Course
from model.course_class import CourseClass
from model.student_result import StudentResult
from model.enrollment import Enrollment
from model.schedule import Schedule
from model.room import Room
from model.building import Building
